# Generated by Django 3.1.7 on 2021-03-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piazza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
