# Generated by Django 3.1.7 on 2021-03-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Piazza', '0003_comment_dislike_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='liked_by',
            new_name='disliked_by',
        ),
    ]
