# Generated by Django 3.1.7 on 2021-03-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piazza', '0005_auto_20210331_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_live',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
